import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { MetadataProps, RootLayoutProps } from './utils/types'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: MetadataProps = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    )
}
