import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { MetadataProps, RootLayoutProps } from './utils/types'

import Header from './components/Header'
import Footer from './components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata: MetadataProps = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
                </body>
        </html>
    )
}
